### ISSUE TITLE
restreamer.list_segments should only list segments

### ISSUE THREAD

**Issue by chrusher** [ekimekim/wubloader#8]
Currently `restreamer.list_segments` lists all non-hidden files in an hour directory. Should it only list files it thinks are segments? A simple way to this is to only return files with the `.ts` file extension? Obviously, there is no guarantee that files with this extension are segments.

**Comment by ekimekim** [comment]
I don't think this is a case we need to worry about. Only segments should exist in these paths, and if something else is accidentially created, it'll get caught when we try to parse the filepath later.

In general I'd like to keep each component as dumb as possible, without extra checks. This keeps the system loosly coupled and allows us to more easily make changes later, as well as reducing the amount of logic in each component. You can't have bugs in guarentees you don't actually make.

TBH I wouldn't have even bothered disallowing hidden files, except I wasn't sure if flask would automatically handle directory traversal attacks for me (eg. trying to get a stream name `..`, which would make a path like `../variant/blah blah`). As it turns out I think it does, so I may go back and remove that restriction.

**Comment by chrusher** [comment]
Fair enough. I'll close this.
